//
// Generated by afu_json_mgr from /filespace/c/chenke/RGBSetMeFree/project/hw/afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "afu"
`define AFU_ACCEL_UUID 128'h9f0c38be_cb5b_45c8_b3d3_b9a3aaef0cb6
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
