//
// Generated by afu_json_mgr from /filespace/c/chenke/RGBSetMeFree/project/hw/afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "afu"
`define AFU_ACCEL_UUID 128'hc7ce8ca4_3648_48a6_89a2_59622d313f5c
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
