##############################################################
#                                                            #
# Xeon(R) + FPGA AFU Simulation Environment                  #
# File generated by ase/scripts/generate_ase_environment.py  #
#                                                            #
##############################################################

SIMULATOR ?= VCS

DUT_VLOG_SRC_LIST = /filespace/c/chenke/RGBSetMeFree/project/sim/vlog_files.list 

ASE_PLATFORM ?= FPGA_PLATFORM_INTG_XEON

